### ISSUE TITLE
Unable to specify jar location or execute gradle task publish 

### ISSUE THREAD

**Issue by huskcasaca** [TheMrMilchmann/gradle-curseforge-publish#15]
Gradle sync is success but not able to publish.

`build.gradle.kts`
```
val curseForgeKey: String by project
val curseForgeId: String by project

publishing {
    repositories.curseForge {
        apiKey.set(curseForgeKey)
    }
    publications.create<CurseForgePublication1>("curseForge") {
        projectID.set(curseForgeId.toInt()) // The CurseForge project ID (required)
        // Specify which game and version the mod/plugin targets (required)
        includeGameVersions { type, version -> type == "minecraft-1-19" && version == "minecraft-1-19-1" }
        artifact {
            changelog = Changelog("Changelog...", ChangelogType.TEXT) // The changelog (required)
            releaseType = ReleaseType.RELEASE // The release type (required)
            displayName = "Effortless Fabric" // A user-friendly name for the project (optional)
        }
    }
}
```

Stacktrace
```
In plugin 'io.github.themrmilchmann.curseforge-publish' type 'io.github.themrmilchmann.gradle.publish.curseforge.tasks.PublishToCurseForgeRepository' property 'publication.publishableFiles' cannot be resolved:  Cannot convert the provided notation to a File or URI: io.github.themrmilchmann.gradle.publish.curseforge.internal.artifacts.PublishArtifactBasedCurseForgeArtifact@593b9989. The following types/formats are supported:  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'. - A String or CharSequence URI, for example 'file:/usr/include'. - A File instance. - A Path instance. - A Directory instance. - A RegularFile instance. - A URI or URL instance. - A TextResource instance. Reason: An input file collection couldn't be resolved, making it impossible to determine task inputs. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#unresolvable_input for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.4.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

Is there any way to specify jar location or handle this error? This project can be found [here](https://github.com/huskcasaca/effortless-fabric). 

Notice: ```curseForgeKey``` and ```curseForgeId``` are in ```gradle.properties.kts```. If you need them please let me know.

Thanks a lot.

**Comment by TheMrMilchmann** [comment]
Hi, this is not actually a stacktrace nor an error. It's a warning that Gradle produces because the plugin currently doesn't implement an internal API correctly. (Unfortunately, the plugin heavily relies on Gradle's internals because there is no official API for custom publications and repositories yet.)

> Is there any way to specify jar location?

I'm not familiar with Fabric's Gradle workflow but, by default, the jar produced by the "jar" task is used. This should probably work. Alternatively, you can configure the main artifact by using one of the `artifact` overloads of `CurseForgePublication`:

```groovy
artifact(tasks.customJarTask) {
    ...
}
```


However, this shouldn't affect publishing and I'm not quite sure if the task actually failed based on your output. Could you please double-check if it really failed and, if it did, run again with the following command and send me the full output:

    ./gradlew publish --info -S


> Notice: **curseForgeKey** and curseForgeId are in gradle.properties.kts. If you need them please let me know.

Don't ever share your API key as that would allow other people to publish to your project.

**Comment by huskcasaca** [comment]
Oh did uploaded successfully, but the gradle output is quite misleading.

Thanks for the help :)

**Comment by TheMrMilchmann** [comment]
You have to use OR (`||`) there instead of AND. Your filter currently only matches if the type is both "minecraft-1-19" and "minecraft-1-19-2" which cannot be true.

**Comment by huskcasaca** [comment]
I tried OR `||` but it doesn't work. I think we should use AND `&&` and `1-19-2` without a `minecraft` prefix .

I tested this and it works

`includeGameVersions { type, version -> type == "minecraft-1-19" && version == "1-19-2" }`

**Comment by TheMrMilchmann** [comment]
Yes, sorry tor the confusion. You are absolutely right.

**Comment by TheMrMilchmann** [comment]
I fixed this in the plugin's documentation and samples. Also, the confusing warning should no longer appear with the upcoming `0.2.0` update (which I plan to release later today).
