### ISSUE TITLE
Add flags to disable mod toolchain integrations

### ISSUE THREAD

**Issue by huskcasaca** [TheMrMilchmann/gradle-curseforge-publish#26]
I believe there is no need to detect the specific mod gradle plugin, whether it's forge, fabric, or any other used in the project and read the minecraft version from them.

In my opinion, this plugin should only focus on publishing JARs to curseforge. The minecraft version should be set through a `gameVersion` property only.

**Comment by TheMrMilchmann** [comment]
Hi @huskcasaca,

The goal of this plugin is to make it as seamless as possible to publish artifacts to CurseForge. This is achieved by following the [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) paradigm: The plugin infers reasonable defaults from your Gradle project's configuration. More information can be inferred from modding framework plugins. However, this does not introduce a dependency on these plugins. The inference is simply an additional mechanism that is decoupled from the remaining functionality of the plugin. Additionally, it is already possible to overwrite the inferred properties.

In the context of #24, I essentially plan to rewrite the entire plugin. As part of this, I will also add properties to disable inference but you will probably not want to use them in most cases.
